# Generated by Django 5.0.7 on 2024-12-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_invitations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip_members',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip_members',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
        migrations.AddField(
            model_name='trip_invitations',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
        migrations.AddField(
            model_name='step_groups',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
        migrations.AddField(
            model_name='tripsteps',
            name='step_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.step_groups'),
        ),
        migrations.AlterUniqueTogether(
            name='trip_members',
            unique_together={('user', 'trip')},
        ),
    ]
