# Generated by Django 5.0.7 on 2025-01-01 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 18, 22, 50, 212126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 18, 22, 50, 212126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='end_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tripsteps',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
