# Generated by Django 5.0.7 on 2025-01-04 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trips_end_date_alter_trips_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 18, 0, 41, 172019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 18, 0, 41, 172019, tzinfo=datetime.timezone.utc)),
        ),
    ]
